### ISSUE TITLE
Message Timestamp in Database

### ISSUE THREAD

**Issue by CyB3RC0nN0R** [informatik-ag-ngl/envoy-server#5]
In der Datenbank erhalten Nachrichten einen Timestamp, der vom Client in der XML-Datei mitgeliefert wird.
Die Uhrzeit wird hier offenbar inkorrekt geparst, weshalb alle Nachrichten für einen Tag dieselbe Uhrzeit im Timestamp haben.

Beispiel (07.10.19) `2019-10-07 02:00:00`

**Comment by derharry333** [comment]
Der Datentyp des Datumfeldes in message_schema.xsd xs:date wurde zu xs:dateTime geändert.
